// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAO-FUg8G2p5LeUEEGDOs7TRa0vz_DEMU',
    appId: '1:1028297714447:web:6e3ce4a8382b11ec01ec7a',
    messagingSenderId: '1028297714447',
    projectId: 'joji-gym-admin',
    authDomain: 'joji-gym-admin.firebaseapp.com',
    storageBucket: 'joji-gym-admin.firebasestorage.app',
    measurementId: 'G-SHFJ86FJC8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYZpx2XtfI6Y5K9unzatNc-90ainrAQrU',
    appId: '1:1028297714447:android:4c37ac4a270a01c101ec7a',
    messagingSenderId: '1028297714447',
    projectId: 'joji-gym-admin',
    storageBucket: 'joji-gym-admin.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8C-Oa-xkmgGzwkOE0PRTISdt3MjxRZG0',
    appId: '1:1028297714447:ios:4d8f00ac6f981b1201ec7a',
    messagingSenderId: '1028297714447',
    projectId: 'joji-gym-admin',
    storageBucket: 'joji-gym-admin.firebasestorage.app',
    iosBundleId: 'com.example.admin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8C-Oa-xkmgGzwkOE0PRTISdt3MjxRZG0',
    appId: '1:1028297714447:ios:4d8f00ac6f981b1201ec7a',
    messagingSenderId: '1028297714447',
    projectId: 'joji-gym-admin',
    storageBucket: 'joji-gym-admin.firebasestorage.app',
    iosBundleId: 'com.example.admin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAO-FUg8G2p5LeUEEGDOs7TRa0vz_DEMU',
    appId: '1:1028297714447:web:0f9646232b89d73501ec7a',
    messagingSenderId: '1028297714447',
    projectId: 'joji-gym-admin',
    authDomain: 'joji-gym-admin.firebaseapp.com',
    storageBucket: 'joji-gym-admin.firebasestorage.app',
    measurementId: 'G-R19T8BTBD9',
  );
}
